using YamlDotNet.Serialization;

namespace Aspire.Hosting.Kamal.Model;

internal static class KamalYamlWriter
{
    private static readonly ISerializer s_serializer = new SerializerBuilder()
        .ConfigureDefaultValuesHandling(
            DefaultValuesHandling.OmitNull | DefaultValuesHandling.OmitEmptyCollections)
        .WithIndentedSequences()
        .Build();

    public static string Serialize(KamalDeployConfig config)
    {
        return "# Generated by Aspire.Hosting.Kamal. See https://kamal-deploy.org/docs/configuration/overview/\n"
            + s_serializer.Serialize(config);
    }
}
