using System.Text.RegularExpressions;

namespace Vensas.Aspire.Hosting.Kamal;

/// <summary>
/// Generates a multi-stage Dockerfile for a .NET project so that <c>kamal deploy</c>
/// can build the app image without any Aspire tooling on the deploy machine.
/// </summary>
internal static partial class DotnetDockerfileGenerator
{
    [GeneratedRegex(@"<TargetFramework(?:s)?>\s*net(\d+\.\d+)", RegexOptions.IgnoreCase)]
    private static partial Regex TargetFrameworkRegex();

    public static string Generate(string projectPath, string contextPath, int appPort)
    {
        var dotnetVersion = DetectDotnetVersion(projectPath);
        var relativeProjectPath = Path.GetRelativePath(contextPath, projectPath).Replace('\\', '/');
        var projectFileName = Path.GetFileName(projectPath);
        var assemblyName = Path.GetFileNameWithoutExtension(projectPath);

        return $"""
            # Generated by Vensas.Aspire.Hosting.Kamal for {projectFileName}
            FROM mcr.microsoft.com/dotnet/sdk:{dotnetVersion} AS build
            WORKDIR /src
            COPY . .
            RUN dotnet publish "{relativeProjectPath}" -c Release -o /app/publish /p:UseAppHost=false

            FROM mcr.microsoft.com/dotnet/aspnet:{dotnetVersion}
            WORKDIR /app
            COPY --from=build /app/publish .
            ENV ASPNETCORE_HTTP_PORTS={appPort}
            EXPOSE {appPort}
            ENTRYPOINT ["dotnet", "{assemblyName}.dll"]
            """;
    }

    public static string DetectDotnetVersion(string projectPath)
    {
        try
        {
            var content = File.ReadAllText(projectPath);
            var match = TargetFrameworkRegex().Match(content);
            if (match.Success)
            {
                return match.Groups[1].Value;
            }
        }
        catch (IOException)
        {
            // Fall through to the default below.
        }

        return "10.0";
    }

    /// <summary>
    /// Walks up from the project file looking for a repository root (a directory containing
    /// a <c>.git</c> directory or a solution file). Falls back to the project directory.
    /// </summary>
    public static string FindRepositoryRoot(string projectPath)
    {
        var directory = new DirectoryInfo(Path.GetDirectoryName(projectPath)!);
        var fallback = directory.FullName;

        for (var current = directory; current is not null; current = current.Parent)
        {
            if (HasGitDirectory(current) || HasSolutionFile(current))
                return current.FullName;
        }

        return fallback;
    }
    
    private static bool HasGitDirectory(DirectoryInfo directory) 
        => Directory.Exists(Path.Combine(directory.FullName, ".git"));
    
    private static bool HasSolutionFile(DirectoryInfo directory)
        => directory.EnumerateFiles("*.sln").Any() || directory.EnumerateFiles("*.slnx").Any();
}
